import { Project, MemoryItem, UserProfile } from '../types/orchestration';
import { AGENT_AVATARS } from './agentRegistry';

export const INITIAL_USER_PROFILE: UserProfile = {
  id: 'user_prime',
  name: 'Alamu Olusike',
  title: 'Principal Creative Director & Founder',
  company: 'Apex Creative Atelier',
  email: 'alamuolusike@gmail.com',
  preferences: {
    designAesthetic: 'editorial_minimal',
    communicationTone: 'executive_concise',
    theme: 'dark',
    autonomousApproval: false,
  },
};

export const INITIAL_PROJECT: Project = {
  id: 'proj_apex_01',
  name: 'Apex Studio — Flagship Architectural Portfolio & Landing Page',
  slug: 'apex-studio-portfolio',
  description: 'A distinguished, high-conversion digital landing page and editorial portfolio for an avant-garde architectural and interior design studio.',
  objective: 'Position Apex as the premier studio for brutalist and minimalist residential architecture, converting high-net-worth patrons and commercial real-estate developers.',
  requirements: [
    'Strict adherence to the 60-30-10 color discipline: deep slate/obsidian canvas with warm travertine accents',
    'Zero pill badges or noisy chips; typography-first editorial hierarchy',
    'Cinematic 16:9 hero section with focused value proposition and unboxed social proof',
    'Interactive 4-column Bento grid spotlighting core commissions with aspect-ratio disciplined photography',
    'WCAG AA accessible contrast for all typographic elements',
    'Dedicated inquiry booking trigger without disruptive popups',
  ],
  status: 'review',
  workflowStage: 'quality_control',
  tasks: [
    {
      id: 'task_001',
      projectId: 'proj_apex_01',
      assignedAgentId: 'samsmith',
      assignedByAgentId: 'sammypopi',
      title: 'Competitive Teardown & High-End Architecture UX Trends',
      description: 'Analyze top 5 award-winning architectural atelier portfolios (e.g. John Pawson, Olson Kundig, Snøhetta). Map conversion touchpoints and layout patterns.',
      status: 'completed',
      priority: 'high',
      stepIndex: 1,
      workflowStage: 'research',
      createdAt: '2026-09-30T07:15:00Z',
      completedAt: '2026-09-30T07:30:00Z',
      deliverable: {
        title: 'Architectural Portfolio UX Benchmark 2026',
        summary: 'High-net-worth clients prioritize quiet confidence over noisy marketing jargon. Portfolios succeed when they lead with unadorned project imagery, concrete spatial metrics, and an intimate founder statement.',
        content: `### Research Insights:
1. **Quiet Authority**: Leading practices avoid generic agency buzzwords like "disruptive". They use precise spatial descriptions: "Cast monolithic concrete", "Cross-laminated timber", "Passive solar alignment".
2. **Visual Rhythm**: Standard 3-column equal cards cause visual fatigue. Asymmetric 4-column Bento layouts with focal anchors increase engagement dwell time by +68%.
3. **Inquiry Mechanism**: High-end clientele disfavor generic forms with 10 fields. A single direct consultation booking mechanism with calendar selection achieves 3.4x higher completion rates.`,
        format: 'markdown',
      },
    },
    {
      id: 'task_002',
      projectId: 'proj_apex_01',
      assignedAgentId: 'samkindle',
      assignedByAgentId: 'sammypopi',
      title: 'Visual Asset Direction & Travertine Material Palette',
      description: 'Curate color tokens and generate high-fidelity photographic assets. Avoid glossy 3D or fake neon glows.',
      status: 'completed',
      priority: 'high',
      stepIndex: 2,
      workflowStage: 'visual_curation',
      createdAt: '2026-09-30T07:32:00Z',
      completedAt: '2026-09-30T07:55:00Z',
      deliverable: {
        title: 'Apex Visual Direction & Material Tokens',
        summary: 'Curated 4 core photographic assets and a 60-30-10 palette anchored in deep volcanic basalt (#0A0A0C), aged plaster (#E5E5E2), and warm Roman travertine (#D4A373).',
        content: `### Visual Tokens:
- **Canvas (60%)**: Volcanic Basalt \`#0A0A0C\`
- **Surfaces (30%)**: Honed Limestone \`#16161A\`, Hairline \`rgba(255,255,255,0.08)\`
- **Accent (10%)**: Roman Travertine \`#D4A373\` (Strictly reserved for primary CTAs and active states)
- **Imagery**: Natural side illumination, organic textures, documentary Leica-style architectural compositions.`,
        format: 'specs',
      },
    },
    {
      id: 'task_003',
      projectId: 'proj_apex_01',
      assignedAgentId: 'samsonite',
      assignedByAgentId: 'sammypopi',
      title: 'Information Architecture & Wireframe Layout Blueprint',
      description: 'Design the 5-phase layout blueprint: Hero, Narrative Kicker, Curated Commissions Bento Grid, Studio Philosophy, and Private Consultation CTA.',
      status: 'completed',
      priority: 'high',
      stepIndex: 3,
      workflowStage: 'design_architecture',
      createdAt: '2026-09-30T08:00:00Z',
      completedAt: '2026-09-30T08:25:00Z',
      deliverable: {
        title: 'Apex Landing Page Wireframe Blueprint v1.2',
        summary: 'Established a 1440px spatial grid with single-elevation depth. No nested card sandwiches. Section transitions paced with subtle hairline dividers.',
        content: `### Section Architecture:
1. **Top Bar**: Single wordmark 'APEX ARCHITECTURE' · Clean 4 text links (Commissions, Philosophy, Monograph, Contact) · Direct 'Inquire' action.
2. **Hero Section**: Typographic statement 'Monolithic Spaces. Intimate Sanctuaries.' + 16:9 cinematic backdrop + Dual action CTAs.
3. **Curated Commissions (Bento Grid)**: 3 asymmetric architectural monographs featuring real floor area, completion year, and spatial program.
4. **Studio Philosophy**: 2-column editorial layout detailing material permanence and sustainable engineering.
5. **Private Consultation**: Direct private intake scheduler.`,
        format: 'specs',
      },
    },
    {
      id: 'task_004',
      projectId: 'proj_apex_01',
      assignedAgentId: 'sammy',
      assignedByAgentId: 'sammypopi',
      title: 'Typography Calibration & Specimen Polish',
      description: 'Audit type scale, pairing harmony, optical tracking for dark mode, tabular figures for project metrics, and text-wrap balance.',
      status: 'completed',
      priority: 'medium',
      stepIndex: 4,
      workflowStage: 'typography_polish',
      createdAt: '2026-09-30T08:26:00Z',
      completedAt: '2026-09-30T08:42:00Z',
      deliverable: {
        title: 'Typographic Specimen & Polish Audit',
        summary: 'Enforced the 2+1 font rule: Plus Jakarta Sans for body prose, Syne/Cabinet display for headlines, and JetBrains Mono with tabular-nums for architectural measurements (sq ft, completion year).',
        content: `### Typographic Specs:
- **Display Face**: Plus Jakarta Sans / Cabinet Grotesk (Optical weight: 600, letter-spacing: -0.02em)
- **Body Face**: Plus Jakarta Sans (Regular 400, line-height: 1.65, max-measure: 68ch)
- **Data & Figures**: JetBrains Mono with \`tabular-nums\` (\`sq ft\`, \`lat/long\`, \`year\`)
- **Headline Balance**: Applied \`text-wrap: balance\` across all section headers to eradicate single-word orphans.`,
        format: 'specs',
      },
    },
    {
      id: 'task_005',
      projectId: 'proj_apex_01',
      assignedAgentId: 'samuel',
      assignedByAgentId: 'sammypopi',
      title: 'Quality Control Audit & Anti-Slop Inspection',
      description: 'Rigorous critique of the integrated layout. Check contrast ratios, zero-pill compliance, and authentic attribution.',
      status: 'in_progress',
      priority: 'critical',
      stepIndex: 5,
      workflowStage: 'quality_control',
      createdAt: '2026-09-30T08:45:00Z',
      critique: {
        reviewerId: 'samuel',
        reviewerName: 'Samuel',
        feedback: 'The layout structure is exceptionally strong and honors the 60-30-10 palette. However, Samsonite initially included a rounded pill capsule on the project status tags. I have flagged this for removal in favor of clean unboxed text with typographic bullet separators (·). Contrast on the travertine CTA button was verified at 6.8:1 (exceeding WCAG AA). Once the pill tags are converted to clean inline metadata, this deliverable is ready for Sammypopi’s final blessing.',
        approved: false,
        revisionRequired: true,
        score: 94,
        timestamp: '2026-09-30T08:52:00Z',
      },
    },
  ],
  assets: [
    {
      id: 'asset_01',
      title: 'Cast Concrete Residence — Lake Lugano',
      category: 'image',
      url: AGENT_AVATARS.samkindle,
      description: 'Monolithic raw concrete facade with deep cantilever, surrounded by alpine mist and natural travertine paving.',
      tags: ['Hero', 'Residential', 'Concrete', 'Minimalist'],
      curatedByAgentId: 'samkindle',
    },
    {
      id: 'asset_02',
      title: 'Aged Travertine & Volcanic Stone Palette',
      category: 'palette',
      url: '#',
      description: 'Primary material palette extracted from natural limestone quarries in Tivoli.',
      tags: ['Palette', '60-30-10', 'Materials'],
      curatedByAgentId: 'samkindle',
    },
    {
      id: 'asset_03',
      title: 'The Kyōto Pavilion — Wood & Shadow',
      category: 'image',
      url: AGENT_AVATARS.samsonite,
      description: 'Charred cedar (Shou Sugi Ban) tea house with framed garden courtyard.',
      tags: ['Commercial', 'Pavilion', 'Timber'],
      curatedByAgentId: 'samkindle',
    },
  ],
  researchNotes: [
    {
      id: 'res_01',
      title: 'High-Net-Worth Spatial Expectations',
      category: 'market',
      insight: 'Patrons of high-end architecture evaluate studios based on material honesty and portfolio restraint. Showing 3 immaculate projects is proven to generate more qualified inquiries than an exhaustive 30-project catalog.',
      recommendedActions: [
        'Curate the hero portfolio down to 3 seminal works',
        'Display structural material specs prominently alongside square footage',
        'Include high-resolution photographs with natural illumination',
      ],
      conductedByAgentId: 'samsmith',
      confidence: 'high',
    },
    {
      id: 'res_02',
      title: 'Conversion Psychology for Architectural Commissions',
      category: 'ux',
      insight: 'Clients rarely purchase off a landing page; they book a private site feasibility consultation. The primary conversion CTA should be a discreet "Request Private Consultation" with explicit timeline expectations.',
      recommendedActions: [
        'Replace generic "Contact Us" with "Inquire for Private Consultation"',
        'State transparent studio capacity (e.g. "Now accepting 3 commissions for 2027")',
      ],
      conductedByAgentId: 'samsmith',
      confidence: 'high',
    },
  ],
  typographySpec: {
    displayFont: 'Plus Jakarta Sans (SemiBold 600)',
    bodyFont: 'Plus Jakarta Sans (Regular 400)',
    monoFont: 'JetBrains Mono (tabular-nums)',
    scaleRatio: '1.250 — Major Third',
    lineHeights: {
      display: '1.15',
      body: '1.65',
    },
    spacingRhythm: '4px baseline with 16px/24px/32px container bounds',
    rationale: 'Clean contemporary sans pairing gives authoritative editorial presence without cold impersonality. Monospace tabular numerals prevent layout jitter in spatial metrics.',
    curatedByAgentId: 'sammy',
  },
  designDraft: {
    headline: 'Monolithic Spaces. Intimate Sanctuaries.',
    subheadline: 'Apex Studio designs bespoke residences and cultural pavilions carved from natural stone, raw timber, and ambient light.',
    heroCta: 'Request Private Consultation',
    secondaryCta: 'Explore Selected Works',
    layoutStructure: ['Top Bar', 'Hero Presence', 'Monograph Showcase', 'Studio Philosophy', 'Consultation Trigger'],
    colorTokens: {
      canvas: '#0A0A0C',
      surface: '#141418',
      textPrimary: '#F4F4F5',
      textMuted: '#A1A1AA',
      accent: '#D4A373',
      border: 'rgba(255, 255, 255, 0.08)',
    },
    sections: [
      {
        id: 'hero',
        name: 'Hero Section',
        kicker: 'Apex Architecture & Spatial Design',
        heading: 'Monolithic Spaces. Intimate Sanctuaries.',
        description: 'We construct timeless architectural sanctuaries that balance raw elemental materials with serene private living.',
      },
      {
        id: 'commissions',
        name: 'Curated Commissions',
        kicker: 'Selected Monographs · 2024–2026',
        heading: 'Architecture of Permanence',
        description: 'Each commission is an unrepeatable dialogue between topography, material honesty, and natural light.',
        items: [
          'Villa Solis · 8,400 sq ft · Lake Como · Cast Concrete & Travertine',
          'The Obsidian House · 5,200 sq ft · Kyoto · Shou Sugi Ban & Basalt',
          'Pavilion IX · 3,100 sq ft · Engadin Valley · Alpine Quartzite',
        ],
      },
      {
        id: 'philosophy',
        name: 'Studio Philosophy',
        kicker: 'Material Discipline',
        heading: 'Built to Outlive the Century',
        description: 'True luxury is the absence of superfluous noise. We do not design for temporary trends. We sculpt space that deepens in character as materials weather and age.',
      },
    ],
    designedByAgentId: 'samsonite',
    version: 1,
  },
  discussions: [
    {
      id: 'disc_001',
      projectId: 'proj_apex_01',
      senderAgentId: 'sammypopi',
      content: 'Team, our patron Alamu has initiated the Apex Studio project. The objective is clear: an uncompromising, editorial architectural landing page. Samsmith, initiate competitive UX research. Samkindle, prepare visual material tokens.',
      type: 'directive',
      timestamp: '2026-09-30T07:05:00Z',
    },
    {
      id: 'disc_002',
      projectId: 'proj_apex_01',
      senderAgentId: 'samsmith',
      recipientAgentId: 'samsonite',
      content: 'I have finalized the research teardown. Samsonite, do not use a standard 3-card grid for the projects. High-end architectural clients want asymmetry and large format photography with clear metric details (floor area, stone type, year).',
      type: 'proposal',
      timestamp: '2026-09-30T07:31:00Z',
      relatedTaskId: 'task_001',
    },
    {
      id: 'disc_003',
      projectId: 'proj_apex_01',
      senderAgentId: 'samsonite',
      recipientAgentId: 'samsmith',
      content: 'Understood, Samsmith. I am implementing a responsive Bento layout with a single dominant hero monograph followed by two paired spatial studies. Samkindle, send over the travertine and raw concrete imagery.',
      type: 'agreement',
      timestamp: '2026-09-30T07:45:00Z',
      relatedTaskId: 'task_003',
    },
    {
      id: 'disc_004',
      projectId: 'proj_apex_01',
      senderAgentId: 'sammy',
      recipientAgentId: 'samsonite',
      content: 'Samsonite, I reviewed the draft. Make sure you apply text-wrap: balance to the main headline "Monolithic Spaces. Intimate Sanctuaries." to prevent "Sanctuaries" from wrapping into an orphan on medium screens. Also enforcing tabular-nums on the 8,400 sq ft metrics.',
      type: 'proposal',
      timestamp: '2026-09-30T08:35:00Z',
      relatedTaskId: 'task_004',
    },
    {
      id: 'disc_005',
      projectId: 'proj_apex_01',
      senderAgentId: 'samuel',
      recipientAgentId: 'samsonite',
      content: 'Critical review: I spotted rounded pill badges on the status tags in your wireframe draft. You know our design constitution strictly prohibits static pill enclosures. Convert them to clean unboxed text separated by "·" characters. Once updated, I will give my formal sign-off.',
      type: 'critique',
      timestamp: '2026-09-30T08:50:00Z',
      relatedTaskId: 'task_005',
    },
    {
      id: 'disc_006',
      projectId: 'proj_apex_01',
      senderAgentId: 'sammypopi',
      recipientAgentId: 'samuel',
      content: 'Excellent catch, Samuel. That is precisely why you lead our quality control. Samsonite has complied, and the metadata is now clean and unboxed. I am preparing the final synthesis for our patron.',
      type: 'directive',
      timestamp: '2026-09-30T08:55:00Z',
    },
  ],
  deliverables: [
    {
      id: 'deliv_001',
      title: 'Apex Studio — Flagship Architectural Landing Page (Live Interactive)',
      type: 'landing_page',
      status: 'reviewed',
      content: 'Complete accessible, high-performance responsive architectural landing page component featuring 60-30-10 palette, travertine CTA accents, unboxed metadata, and responsive Bento showcase.',
      createdAt: '2026-09-30T08:58:00Z',
    },
    {
      id: 'deliv_002',
      title: 'Full Design Specification & Brand Token Deck',
      type: 'design_spec',
      status: 'final',
      content: 'Comprehensive document covering color values, typographic scale, section spacing rules, image aspect ratio requirements, and consultation funnel logic.',
      createdAt: '2026-09-30T08:56:00Z',
    },
  ],
  history: [
    {
      id: 'hist_01',
      agentId: 'sammypopi',
      action: 'Project Initialized',
      detail: 'Deconstructed user brief into 5 sequential agent tasks.',
      timestamp: '2026-09-30T07:00:00Z',
    },
    {
      id: 'hist_02',
      agentId: 'samsmith',
      action: 'Research Completed',
      detail: 'Delivered Architectural Portfolio UX Benchmark 2026.',
      timestamp: '2026-09-30T07:30:00Z',
    },
    {
      id: 'hist_03',
      agentId: 'samkindle',
      action: 'Assets Curated',
      detail: 'Configured volcanic basalt & travertine material palette.',
      timestamp: '2026-09-30T07:55:00Z',
    },
    {
      id: 'hist_04',
      agentId: 'samsonite',
      action: 'Wireframe Synthesized',
      detail: 'Generated 1440px desktop baseline with single-elevation layout.',
      timestamp: '2026-09-30T08:25:00Z',
    },
    {
      id: 'hist_05',
      agentId: 'sammy',
      action: 'Typography Calibrated',
      detail: 'Applied 2+1 font rule with tabular numerals and balanced headlines.',
      timestamp: '2026-09-30T08:42:00Z',
    },
    {
      id: 'hist_06',
      agentId: 'samuel',
      action: 'QC Inspection',
      detail: 'Audited layout; flagged pill badges for removal; contrast confirmed 6.8:1.',
      timestamp: '2026-09-30T08:52:00Z',
    },
  ],
  createdAt: '2026-09-30T07:00:00Z',
  updatedAt: '2026-09-30T08:58:00Z',
};

export const INITIAL_MEMORIES: MemoryItem[] = [
  // 1. User Memory
  {
    id: 'mem_user_01',
    category: 'user',
    title: 'Design Aesthetic & Taste Preferences',
    content: 'Patron Alamu prefers quiet luxury, monolithic brutalism, and editorial typography. Dislikes generic AI slop, floating neon badges, and empty marketing clichés.',
    tags: ['taste', 'aesthetic', 'editorial'],
    importance: 'critical',
    createdAt: '2026-09-30T06:00:00Z',
    updatedAt: '2026-09-30T06:00:00Z',
  },
  {
    id: 'mem_user_02',
    category: 'user',
    title: 'Communication & Delegation Style',
    content: 'Prefers executive summaries with clear actionable recommendations rather than raw verbose logs. Values honest critique and independent quality evaluation.',
    tags: ['communication', 'executive'],
    importance: 'high',
    createdAt: '2026-09-30T06:10:00Z',
    updatedAt: '2026-09-30T06:10:00Z',
  },
  // 2. Project Memory
  {
    id: 'mem_proj_01',
    category: 'project',
    title: 'Apex Studio Color Tokens & Material Restraint',
    content: 'Approved palette: 60% Volcanic Basalt (#0A0A0C), 30% Honed Slate (#16161A), 10% Roman Travertine (#D4A373). Never mix warm and cool accents.',
    targetId: 'proj_apex_01',
    tags: ['color', 'tokens', 'material'],
    importance: 'critical',
    createdAt: '2026-09-30T07:40:00Z',
    updatedAt: '2026-09-30T07:40:00Z',
  },
  {
    id: 'mem_proj_02',
    category: 'project',
    title: 'Conversion Goal & Inquiry Flow',
    content: 'Target outcome is private consultation bookings for projects exceeding $2.5M in construction budget. Avoid generic multi-step checkout forms.',
    targetId: 'proj_apex_01',
    tags: ['conversion', 'cta'],
    importance: 'high',
    createdAt: '2026-09-30T07:45:00Z',
    updatedAt: '2026-09-30T07:45:00Z',
  },
  // 3. Agent Memory
  {
    id: 'mem_agent_samuel',
    category: 'agent',
    title: 'Samuel QC Rule: Anti-Slop Strict Enforcement',
    content: 'Always reject static pill capsules around status/metadata tags and check for headline orphans. Samsonite tends to slip in pill badges unless checked.',
    targetId: 'samuel',
    tags: ['qc', 'anti-slop', 'rules'],
    importance: 'critical',
    createdAt: '2026-09-30T08:00:00Z',
    updatedAt: '2026-09-30T08:00:00Z',
  },
  {
    id: 'mem_agent_sammy',
    category: 'agent',
    title: 'Sammy Rule: Tabular Numerals Mandatory',
    content: 'All architectural measurements (sq ft, year, lat/long) must use JetBrains Mono or tabular-nums to prevent visual jitter.',
    targetId: 'sammy',
    tags: ['typography', 'tabular-nums'],
    importance: 'high',
    createdAt: '2026-09-30T08:10:00Z',
    updatedAt: '2026-09-30T08:10:00Z',
  },
  // 4. Conversation History
  {
    id: 'mem_conv_01',
    category: 'conversation',
    title: 'Key Decision: Monolithic Architecture Focus',
    content: 'Alamu emphasized that the portfolio should focus on monolithic stone and concrete residences rather than generic commercial towers.',
    tags: ['decision', 'brief'],
    importance: 'high',
    createdAt: '2026-09-30T07:10:00Z',
    updatedAt: '2026-09-30T07:10:00Z',
  },
  // 5. Knowledge & Resources
  {
    id: 'mem_know_01',
    category: 'knowledge',
    title: 'Design Constitution: 2+1 Font Pairing Rule',
    content: 'Every application must use at most two font families (1 expressive display face + 1 readable body face) plus at most one monospace outlier for data metrics.',
    tags: ['constitution', 'typography'],
    importance: 'critical',
    createdAt: '2026-09-30T05:00:00Z',
    updatedAt: '2026-09-30T05:00:00Z',
  },
  {
    id: 'mem_know_02',
    category: 'knowledge',
    title: 'Anti-Slop Protocol: Pill Enclosure Ban',
    content: 'Never wrap metadata (dates, categories, status labels) in rounded pill boxes or colored capsules. Render metadata as clean, unboxed text with subtle typographic separators (·).',
    tags: ['constitution', 'anti-slop'],
    importance: 'critical',
    createdAt: '2026-09-30T05:00:00Z',
    updatedAt: '2026-09-30T05:00:00Z',
  },
];
