import React, { useState } from 'react';
import { 
  FolderKanban, 
  Eye, 
  FileText, 
  Compass, 
  Palette, 
  Type, 
  CheckCircle2, 
  AlertTriangle, 
  Download, 
  Code, 
  Copy, 
  Check, 
  Sparkles,
  ArrowRight,
  ExternalLink,
  ShieldAlert
} from 'lucide-react';
import { Project, Agent } from '../types/orchestration';

interface ProjectWorkspaceProps {
  project: Project;
  agents: Agent[];
  onUpdateRequirement?: (index: number, value: string) => void;
  onRunWorkflow: () => void;
  isWorkflowRunning: boolean;
}

export const ProjectWorkspace: React.FC<ProjectWorkspaceProps> = ({
  project,
  agents,
  onRunWorkflow,
  isWorkflowRunning,
}) => {
  const [activeSubTab, setActiveSubTab] = useState<
    'preview' | 'brief' | 'research' | 'assets' | 'typography' | 'critique' | 'code'
  >('preview');
  const [copiedCode, setCopiedCode] = useState(false);
  const [inquiryModalOpen, setInquiryModalOpen] = useState(false);
  const [inquirySubmitted, setInquirySubmitted] = useState(false);

  const samuel = agents.find(a => a.id === 'samuel');
  const qcTask = project.tasks.find(t => t.assignedAgentId === 'samuel');

  const handleCopyCode = () => {
    const codeSnippet = `// Apex Studio Landing Page Component
// Generated by Sammypopi Multi-Agent Atelier (Samsonite, Sammy, Samkindle, Samuel)
export default function ApexLandingPage() {
  return (
    <div className="bg-[#0A0A0C] text-[#F4F4F5] min-h-screen">
      <header className="border-b border-white/10 px-6 py-4 flex justify-between items-center">
        <span className="font-semibold tracking-tight text-lg">Apex Architecture</span>
        <nav className="flex gap-6 text-sm text-neutral-400">
          <a href="#commissions">Commissions</a>
          <a href="#philosophy">Philosophy</a>
          <a href="#inquiry">Inquire</a>
        </nav>
      </header>
      <main className="max-w-7xl mx-auto px-6 py-20">
        <h1 className="text-5xl font-bold tracking-tight text-balance">
          ${project.designDraft.headline}
        </h1>
        <p className="mt-4 text-neutral-400 text-lg max-w-2xl">
          ${project.designDraft.subheadline}
        </p>
      </main>
    </div>
  );
}`;
    navigator.clipboard.writeText(codeSnippet);
    setCopiedCode(true);
    setTimeout(() => setCopiedCode(false), 2000);
  };

  return (
    <div className="space-y-5">
      
      {/* Workspace Header */}
      <div className="rounded-xl border border-neutral-800 bg-neutral-900/60 p-5">
        <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <div className="flex items-center gap-2 text-xs text-neutral-400">
              <span>Project Atelier</span>
              <span>·</span>
              <span className="font-mono text-amber-400">{project.id}</span>
              <span>·</span>
              <span className="text-emerald-400">Status: {project.status.toUpperCase()}</span>
            </div>
            <h1 className="mt-1 text-lg font-semibold text-neutral-100">
              {project.name}
            </h1>
            <p className="mt-1 text-xs text-neutral-400 max-w-3xl leading-relaxed">
              {project.description}
            </p>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={() => setActiveSubTab('preview')}
              className={`flex items-center gap-1.5 rounded-lg border px-3 py-1.5 text-xs font-medium transition-colors ${
                activeSubTab === 'preview'
                  ? 'border-amber-400/60 bg-amber-400/10 text-amber-300'
                  : 'border-neutral-800 bg-neutral-900 text-neutral-400 hover:text-neutral-200'
              }`}
            >
              <Eye className="h-3.5 w-3.5" />
              <span>Live Deliverable Preview</span>
            </button>
          </div>
        </div>

        {/* Sub-navigation tabs (Interactive filter controls allowed) */}
        <div className="mt-5 flex overflow-x-auto border-t border-neutral-800/80 pt-3 gap-2 scrollbar-none">
          {[
            { id: 'preview', label: 'Live Page Preview', icon: Eye },
            { id: 'brief', label: 'Brief & Requirements', icon: FileText },
            { id: 'research', label: 'Research (Samsmith)', icon: Compass },
            { id: 'assets', label: 'Visual Assets (Samkindle)', icon: Palette },
            { id: 'typography', label: 'Typography & Layout', icon: Type },
            { id: 'critique', label: 'QC & Audit (Samuel)', icon: ShieldAlert },
            { id: 'code', label: 'Code & Deliverable', icon: Code },
          ].map(tab => {
            const Icon = tab.icon;
            const isActive = activeSubTab === tab.id;
            return (
              <button
                key={tab.id}
                onClick={() => setActiveSubTab(tab.id as any)}
                className={`flex items-center gap-1.5 whitespace-nowrap rounded-md px-3 py-1.5 text-xs font-medium transition-all ${
                  isActive
                    ? 'bg-neutral-800 text-amber-300 shadow-sm'
                    : 'text-neutral-400 hover:text-neutral-200 hover:bg-neutral-900/60'
                }`}
              >
                <Icon className="h-3.5 w-3.5" />
                <span>{tab.label}</span>
              </button>
            );
          })}
        </div>
      </div>

      {/* Tab: LIVE LANDING PAGE PREVIEW */}
      {activeSubTab === 'preview' && (
        <div className="space-y-4">
          
          {/* Deliverable Toolbar */}
          <div className="flex items-center justify-between rounded-lg border border-neutral-800 bg-neutral-950 px-4 py-2.5 text-xs">
            <div className="flex items-center gap-2 text-neutral-400">
              <span className="h-2 w-2 rounded-full bg-emerald-400" />
              <span className="font-medium text-neutral-200">Apex Studio Landing Page</span>
              <span>·</span>
              <span>Rendered with Tailwind v4 & Plus Jakarta Sans</span>
            </div>

            <div className="flex items-center gap-3">
              <button
                onClick={handleCopyCode}
                className="flex items-center gap-1 text-xs text-neutral-400 hover:text-neutral-200 transition-colors"
              >
                {copiedCode ? <Check className="h-3.5 w-3.5 text-emerald-400" /> : <Copy className="h-3.5 w-3.5" />}
                <span>{copiedCode ? 'Copied' : 'Copy JSX'}</span>
              </button>
            </div>
          </div>

          {/* Actual Rendered Landing Page (Single-Elevation, Anti-Slop Discipline) */}
          <div className="overflow-hidden rounded-xl border border-neutral-800 bg-[#0A0A0C] text-[#F4F4F5] shadow-2xl">
            
            {/* Top Bar Contract: Zone 1 (Wordmark) · Zone 2 (4 clean links) · Zone 3 (1 action) */}
            <header className="flex items-center justify-between border-b border-white/[0.08] px-6 py-4">
              <div className="flex items-center gap-2">
                <span className="text-base font-semibold tracking-tight text-neutral-100">
                  Apex Architecture
                </span>
              </div>

              <nav className="hidden md:flex items-center gap-6 text-xs text-neutral-400 font-medium">
                <a href="#commissions" className="hover:text-neutral-100 transition-colors">Commissions</a>
                <a href="#philosophy" className="hover:text-neutral-100 transition-colors">Philosophy</a>
                <a href="#monographs" className="hover:text-neutral-100 transition-colors">Monographs</a>
                <a href="#inquiry" className="hover:text-neutral-100 transition-colors">Atelier</a>
              </nav>

              <div>
                <button
                  onClick={() => setInquiryModalOpen(true)}
                  className="rounded-md bg-[#D4A373] px-3.5 py-1.5 text-xs font-semibold text-neutral-950 hover:bg-[#e0b589] transition-colors whitespace-nowrap"
                >
                  Inquire
                </button>
              </div>
            </header>

            {/* Hero Section: 60-30-10 color discipline, text-wrap: balance, unboxed social proof */}
            <section className="relative px-6 pt-16 pb-20 sm:px-12 lg:pt-24 lg:pb-28 border-b border-white/[0.06]">
              <div className="max-w-4xl space-y-6">
                
                {/* 1-line unboxed text kicker (NO pill boxes) */}
                <div className="flex items-center gap-2 text-xs text-[#D4A373] font-mono">
                  <span>Apex Atelier</span>
                  <span aria-hidden="true">·</span>
                  <span>Residential & Cultural Sanctuaries</span>
                  <span aria-hidden="true">·</span>
                  <span>Est. 2018</span>
                </div>

                {/* Display Headline with text-wrap: balance to prevent orphan single words */}
                <h1 className="text-4xl sm:text-5xl lg:text-6xl font-semibold tracking-tight leading-[1.12] text-balance text-neutral-100">
                  {project.designDraft.headline}
                </h1>

                {/* Body Prose constrained to 68ch measure */}
                <p className="max-w-[68ch] text-base text-neutral-400 leading-relaxed">
                  {project.designDraft.subheadline}
                </p>

                {/* Actions & Proof */}
                <div className="pt-4 flex flex-wrap items-center gap-4">
                  <button
                    onClick={() => setInquiryModalOpen(true)}
                    className="rounded-md bg-[#D4A373] px-5 py-2.5 text-xs font-semibold text-neutral-950 hover:bg-[#e0b589] transition-colors"
                  >
                    {project.designDraft.heroCta}
                  </button>
                  <a
                    href="#commissions"
                    className="rounded-md border border-neutral-800 bg-neutral-900/60 px-5 py-2.5 text-xs font-medium text-neutral-300 hover:border-neutral-700 transition-colors"
                  >
                    {project.designDraft.secondaryCta}
                  </a>
                </div>

                {/* Unboxed Editorial Proof (Zero pills) */}
                <div className="pt-8 flex flex-wrap items-center gap-6 text-xs text-neutral-500 border-t border-white/[0.06]">
                  <div>
                    <span className="font-mono text-neutral-300 tabular-nums font-semibold">14</span> Architectural Monographs Completed
                  </div>
                  <span aria-hidden="true">·</span>
                  <div>
                    <span className="font-mono text-neutral-300 tabular-nums font-semibold">100%</span> Sustainable Cross-Laminated Timber & Stone
                  </div>
                  <span aria-hidden="true">·</span>
                  <div>
                    <span className="font-mono text-neutral-300 tabular-nums font-semibold">2027</span> Commission Intake Open
                  </div>
                </div>

              </div>
            </section>

            {/* Commissions Section: Bento Grid layout (Samsonite) with tabular metrics (Sammy) */}
            <section id="commissions" className="px-6 py-16 sm:px-12 border-b border-white/[0.06]">
              <div className="flex flex-col sm:flex-row sm:items-end sm:justify-between mb-10">
                <div>
                  <div className="text-xs text-[#D4A373] font-mono">Curated Portfolio</div>
                  <h2 className="mt-1 text-2xl sm:text-3xl font-semibold tracking-tight text-neutral-100">
                    Selected Architectural Commissions
                  </h2>
                </div>
                <p className="mt-2 sm:mt-0 text-xs text-neutral-400 max-w-md">
                  Each structure is an unrepeatable dialogue between natural topography and material permanence.
                </p>
              </div>

              {/* Bento Grid: 1 large card + 2 paired monographs */}
              <div className="grid grid-cols-1 md:grid-cols-12 gap-6">
                
                {/* Large Monograph (8 cols) */}
                <div className="md:col-span-8 rounded-xl border border-white/[0.08] bg-[#141418] p-6 space-y-4">
                  <div className="flex items-center justify-between text-xs text-neutral-400">
                    <span>Villa Solis</span>
                    <span className="font-mono text-neutral-300 tabular-nums">Completed 2025</span>
                  </div>
                  <h3 className="text-xl font-semibold text-neutral-100">
                    Cast Monolithic Residence · Lake Como
                  </h3>
                  <p className="text-xs text-neutral-400 leading-relaxed">
                    Sculpted directly into alpine limestone. Deep cantilevered overhangs frame panoramic lake views while geothermal radiant cooling maintains net-zero operational balance.
                  </p>
                  
                  {/* Clean unboxed architectural metadata */}
                  <div className="pt-4 flex flex-wrap items-center gap-4 text-xs text-neutral-400 border-t border-white/[0.06]">
                    <span>Floor Area: <span className="font-mono text-neutral-200 tabular-nums">8,400 sq ft</span></span>
                    <span aria-hidden="true">·</span>
                    <span>Material: Raw Concrete & Roman Travertine</span>
                    <span aria-hidden="true">·</span>
                    <span>Program: Private Residence</span>
                  </div>
                </div>

                {/* Secondary Monograph 1 (4 cols) */}
                <div className="md:col-span-4 rounded-xl border border-white/[0.08] bg-[#141418] p-6 space-y-4">
                  <div className="flex items-center justify-between text-xs text-neutral-400">
                    <span>The Obsidian House</span>
                    <span className="font-mono text-neutral-300 tabular-nums">Kyōto · 2024</span>
                  </div>
                  <h3 className="text-lg font-semibold text-neutral-100">
                    Charred Cedar Sanctuary
                  </h3>
                  <p className="text-xs text-neutral-400 leading-relaxed">
                    Traditional Shou Sugi Ban timber skin protecting an intimate moss courtyard.
                  </p>
                  <div className="pt-4 text-xs text-neutral-400 border-t border-white/[0.06]">
                    <span>Area: <span className="font-mono text-neutral-200 tabular-nums">5,200 sq ft</span></span>
                    <span className="mx-2">·</span>
                    <span>Basalt Paving</span>
                  </div>
                </div>

                {/* Secondary Monograph 2 (12 cols full width) */}
                <div className="md:col-span-12 rounded-xl border border-white/[0.08] bg-[#141418] p-6 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
                  <div>
                    <div className="text-xs text-[#D4A373] font-mono">Pavilion IX · Engadin Valley, Switzerland</div>
                    <h3 className="text-lg font-semibold text-neutral-100 mt-1">
                      High-Altitude Alpine Quartzite Meditation Space
                    </h3>
                  </div>
                  <div className="flex items-center gap-4 text-xs text-neutral-400">
                    <span>Elevation: <span className="font-mono text-neutral-200 tabular-nums">1,820 m</span></span>
                    <span>·</span>
                    <span>Area: <span className="font-mono text-neutral-200 tabular-nums">3,100 sq ft</span></span>
                    <span>·</span>
                    <span className="text-emerald-400">ArchDaily Finalist 2026</span>
                  </div>
                </div>

              </div>
            </section>

            {/* Philosophy Section */}
            <section id="philosophy" className="px-6 py-16 sm:px-12 border-b border-white/[0.06]">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-10 items-center">
                <div>
                  <div className="text-xs text-[#D4A373] font-mono">Studio Philosophy</div>
                  <h2 className="mt-2 text-2xl sm:text-3xl font-semibold tracking-tight text-neutral-100">
                    Material Honesty Over Superficial Trends
                  </h2>
                </div>
                <div className="space-y-4 text-xs text-neutral-400 leading-relaxed">
                  <p>
                    We reject the disposable visual fads of contemporary construction. Our structures are conceived to weather, darken, and gain majesty over decades.
                  </p>
                  <p>
                    Every joint, shadow gap, and thermal plane is engineered with uncompromising mathematical rigor. When you enter an Apex residence, silence takes shape.
                  </p>
                </div>
              </div>
            </section>

            {/* Consultation CTA Section */}
            <section id="inquiry" className="px-6 py-16 sm:px-12 text-center bg-gradient-to-b from-transparent to-neutral-900/40">
              <div className="max-w-2xl mx-auto space-y-4">
                <div className="text-xs text-[#D4A373] font-mono">Commission Intake 2027</div>
                <h2 className="text-3xl sm:text-4xl font-semibold tracking-tight text-neutral-100">
                  Begin Your Architectural Monograph
                </h2>
                <p className="text-xs text-neutral-400 leading-relaxed">
                  Apex accepts a limited quota of four private residential commissions per calendar year. Request a private feasibility consultation with Principal Alamu Olusike.
                </p>
                <div className="pt-4">
                  <button
                    onClick={() => setInquiryModalOpen(true)}
                    className="rounded-md bg-[#D4A373] px-6 py-3 text-xs font-semibold text-neutral-950 hover:bg-[#e0b589] transition-colors"
                  >
                    Request Private Consultation
                  </button>
                </div>
              </div>
            </section>

            {/* Quiet Footer */}
            <footer className="border-t border-white/[0.08] px-6 py-6 sm:px-12 flex flex-col sm:flex-row items-center justify-between text-xs text-neutral-500 gap-2">
              <div>© 2026 Apex Architecture Atelier. All rights reserved.</div>
              <div className="flex gap-4">
                <a href="#commissions" className="hover:text-neutral-400">Zurich</a>
                <span>·</span>
                <a href="#commissions" className="hover:text-neutral-400">Kyoto</a>
                <span>·</span>
                <a href="#commissions" className="hover:text-neutral-400">New York</a>
              </div>
            </footer>

          </div>

          {/* Interactive Consultation Modal */}
          {inquiryModalOpen && (
            <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4">
              <div className="w-full max-w-md rounded-xl border border-neutral-800 bg-neutral-950 p-6 space-y-4 shadow-2xl">
                <div className="flex items-center justify-between border-b border-neutral-800 pb-3">
                  <div>
                    <h3 className="text-sm font-semibold text-neutral-100">Private Consultation Request</h3>
                    <div className="text-xs text-neutral-400">Direct intake for 2027 commissions</div>
                  </div>
                  <button
                    onClick={() => setInquiryModalOpen(false)}
                    className="text-neutral-400 hover:text-neutral-200"
                  >
                    ✕
                  </button>
                </div>

                {inquirySubmitted ? (
                  <div className="py-6 text-center space-y-2">
                    <CheckCircle2 className="h-8 w-8 text-emerald-400 mx-auto" />
                    <div className="text-sm font-medium text-neutral-200">Consultation Dispatched</div>
                    <p className="text-xs text-neutral-400">
                      Our atelier director will contact you within 24 business hours with our feasibility packet.
                    </p>
                  </div>
                ) : (
                  <form
                    onSubmit={(e) => {
                      e.preventDefault();
                      setInquirySubmitted(true);
                      setTimeout(() => {
                        setInquirySubmitted(false);
                        setInquiryModalOpen(false);
                      }, 2200);
                    }}
                    className="space-y-3 text-xs"
                  >
                    <div>
                      <label className="text-neutral-400">Full Name</label>
                      <input
                        type="text"
                        required
                        placeholder="e.g. Eleanor Vance"
                        className="mt-1 w-full rounded border border-neutral-800 bg-neutral-900 px-3 py-1.5 text-neutral-100 focus:outline-none focus:border-amber-400"
                      />
                    </div>

                    <div>
                      <label className="text-neutral-400">Email Address</label>
                      <input
                        type="email"
                        required
                        placeholder="e.g. eleanor@atelier.com"
                        className="mt-1 w-full rounded border border-neutral-800 bg-neutral-900 px-3 py-1.5 text-neutral-100 focus:outline-none focus:border-amber-400"
                      />
                    </div>

                    <div>
                      <label className="text-neutral-400">Project Location & Est. Budget</label>
                      <input
                        type="text"
                        required
                        placeholder="e.g. Lake Como, Italy · $4.5M+"
                        className="mt-1 w-full rounded border border-neutral-800 bg-neutral-900 px-3 py-1.5 text-neutral-100 focus:outline-none focus:border-amber-400"
                      />
                    </div>

                    <div className="pt-2 flex justify-end gap-2">
                      <button
                        type="button"
                        onClick={() => setInquiryModalOpen(false)}
                        className="rounded px-3 py-1.5 text-neutral-400 hover:text-neutral-200"
                      >
                        Cancel
                      </button>
                      <button
                        type="submit"
                        className="rounded bg-[#D4A373] px-4 py-1.5 font-semibold text-neutral-950 hover:bg-[#e0b589]"
                      >
                        Submit Request
                      </button>
                    </div>
                  </form>
                )}
              </div>
            </div>
          )}
        </div>
      )}

      {/* Tab: BRIEF & REQUIREMENTS */}
      {activeSubTab === 'brief' && (
        <div className="rounded-xl border border-neutral-800 bg-neutral-900/60 p-6 space-y-6">
          <div>
            <h3 className="text-sm font-semibold text-neutral-200">Project Objective & Strategic Mandate</h3>
            <p className="mt-1.5 text-xs text-neutral-300 leading-relaxed">
              {project.objective}
            </p>
          </div>

          <div>
            <h3 className="text-sm font-semibold text-neutral-200">Architectural Requirements (Phase 1 Baseline)</h3>
            <div className="mt-3 space-y-2">
              {project.requirements.map((req, i) => (
                <div
                  key={i}
                  className="flex items-start gap-2.5 rounded-lg border border-neutral-800 bg-neutral-950/80 p-3 text-xs text-neutral-300"
                >
                  <CheckCircle2 className="h-4 w-4 text-emerald-400 shrink-0 mt-0.5" />
                  <span className="leading-relaxed">{req}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* Tab: RESEARCH NOTES (Samsmith) */}
      {activeSubTab === 'research' && (
        <div className="space-y-4">
          <div className="rounded-xl border border-neutral-800 bg-neutral-900/60 p-5">
            <div className="flex items-center justify-between border-b border-neutral-800 pb-3">
              <div>
                <h3 className="text-sm font-semibold text-neutral-200">
                  UX & Competitive Intelligence
                </h3>
                <div className="text-xs text-neutral-400">
                  Conducted by Samsmith · Trend Analysis & Teardowns
                </div>
              </div>
              <span className="font-mono text-xs text-sky-400">2 Verified Insights</span>
            </div>

            <div className="mt-4 space-y-4">
              {project.researchNotes.map(item => (
                <div
                  key={item.id}
                  className="rounded-lg border border-neutral-800 bg-neutral-950 p-4 text-xs space-y-2"
                >
                  <div className="flex items-center justify-between">
                    <h4 className="font-semibold text-neutral-200">{item.title}</h4>
                    <span className="text-[10px] uppercase font-mono text-neutral-400">
                      {item.category} · {item.confidence} confidence
                    </span>
                  </div>

                  <p className="text-neutral-300 leading-relaxed">{item.insight}</p>

                  <div className="pt-2 border-t border-neutral-900">
                    <span className="text-[11px] text-neutral-400">Strategic Actions:</span>
                    <ul className="mt-1 space-y-1">
                      {item.recommendedActions.map((action, idx) => (
                        <li key={idx} className="flex items-center gap-1.5 text-neutral-300">
                          <span className="text-sky-400">·</span>
                          <span>{action}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* Tab: VISUAL ASSETS (Samkindle) */}
      {activeSubTab === 'assets' && (
        <div className="space-y-4">
          <div className="rounded-xl border border-neutral-800 bg-neutral-900/60 p-5">
            <h3 className="text-sm font-semibold text-neutral-200">
              60-30-10 Color System & Material Curations
            </h3>
            <p className="text-xs text-neutral-400 mt-0.5">
              Curated by Samkindle. Banned: neon glows, floating plastic 3D spheres.
            </p>

            {/* 60-30-10 Distribution Bar */}
            <div className="mt-4 space-y-2">
              <div className="flex h-5 w-full overflow-hidden rounded-md border border-neutral-700">
                <div style={{ width: '60%', backgroundColor: '#0A0A0C' }} title="60% Canvas (Volcanic Basalt)" />
                <div style={{ width: '30%', backgroundColor: '#16161A' }} title="30% Surfaces (Honed Limestone)" />
                <div style={{ width: '10%', backgroundColor: '#D4A373' }} title="10% Accent (Roman Travertine)" />
              </div>
              <div className="flex justify-between text-[11px] font-mono text-neutral-400">
                <span>60% Canvas: #0A0A0C</span>
                <span>30% Surfaces: #16161A</span>
                <span className="text-amber-400 font-semibold">10% Travertine: #D4A373</span>
              </div>
            </div>

            {/* Assets Gallery */}
            <div className="mt-6 grid grid-cols-1 md:grid-cols-3 gap-4">
              {project.assets.map(asset => (
                <div key={asset.id} className="rounded-lg border border-neutral-800 bg-neutral-950 p-3 text-xs space-y-2">
                  <div className="text-neutral-200 font-medium">{asset.title}</div>
                  <p className="text-neutral-400 text-[11px] line-clamp-2">{asset.description}</p>
                  <div className="flex flex-wrap gap-1 text-[10px] text-neutral-400 font-mono">
                    {asset.tags.map(t => (
                      <span key={t} className="bg-neutral-900 px-1.5 py-0.5 rounded border border-neutral-800">
                        {t}
                      </span>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* Tab: TYPOGRAPHY & LAYOUT (Sammy & Samsonite) */}
      {activeSubTab === 'typography' && (
        <div className="rounded-xl border border-neutral-800 bg-neutral-900/60 p-5 space-y-6">
          <div>
            <h3 className="text-sm font-semibold text-neutral-200">
              The 2+1 Font Rule Specification
            </h3>
            <p className="text-xs text-neutral-400 mt-0.5">
              Curated by Sammy. Strict rule: at most 2 font families + 1 monospace outlier for metrics.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-xs">
            <div className="rounded-lg border border-neutral-800 bg-neutral-950 p-4 space-y-2">
              <span className="text-[11px] text-neutral-400 font-mono">Display / Hero Headline</span>
              <div className="text-base font-semibold text-neutral-100">
                {project.typographySpec.displayFont}
              </div>
              <p className="text-neutral-400 text-[11px]">
                Applied with optical compensation, tracking -0.02em, and text-wrap: balance.
              </p>
            </div>

            <div className="rounded-lg border border-neutral-800 bg-neutral-950 p-4 space-y-2">
              <span className="text-[11px] text-neutral-400 font-mono">Body Prose</span>
              <div className="text-base font-semibold text-neutral-100">
                {project.typographySpec.bodyFont}
              </div>
              <p className="text-neutral-400 text-[11px]">
                Measure bounded to 65–75ch, line-height 1.65 for fatigue-free reading.
              </p>
            </div>

            <div className="rounded-lg border border-neutral-800 bg-neutral-950 p-4 space-y-2">
              <span className="text-[11px] text-neutral-400 font-mono">Tabular Metrics & Figures</span>
              <div className="text-base font-semibold text-amber-400 font-mono">
                {project.typographySpec.monoFont}
              </div>
              <p className="text-neutral-400 text-[11px]">
                Strictly tabular-nums for vertical alignment of dimensions and dates.
              </p>
            </div>
          </div>
        </div>
      )}

      {/* Tab: QUALITY CONTROL & CRITIQUE (Samuel) */}
      {activeSubTab === 'critique' && (
        <div className="rounded-xl border border-neutral-800 bg-neutral-900/60 p-5 space-y-5">
          <div className="flex items-center justify-between border-b border-neutral-800 pb-3">
            <div className="flex items-center gap-2">
              <ShieldAlert className="h-5 w-5 text-rose-400" />
              <div>
                <h3 className="text-sm font-semibold text-neutral-200">
                  Samuel's Quality Assurance & Anti-Slop Audit
                </h3>
                <div className="text-xs text-neutral-400">
                  Uncompromising peer review before final Maestro sign-off
                </div>
              </div>
            </div>

            <div className="text-right">
              <span className="text-xs font-mono text-emerald-400">Contrast: 6.8:1 (PASS)</span>
            </div>
          </div>

          {qcTask?.critique && (
            <div className="rounded-lg border border-rose-900/40 bg-rose-950/20 p-4 text-xs space-y-3">
              <div className="flex items-center justify-between text-rose-300 font-semibold">
                <span>Inspector Verdict: {qcTask.critique.reviewerName}</span>
                <span className="font-mono text-[11px]">Audit Timestamp: {new Date(qcTask.critique.timestamp).toLocaleTimeString()}</span>
              </div>
              <p className="text-neutral-300 leading-relaxed">
                {qcTask.critique.feedback}
              </p>
            </div>
          )}

          {/* Constitution Checklist */}
          <div className="space-y-2 text-xs">
            <span className="font-semibold text-neutral-300">Design Constitution Audit Checklist:</span>
            {[
              { rule: 'Zero-Pill Discipline: No static metadata wrapped in colored capsule pill badges', pass: true },
              { rule: 'Anti-Slop Banned: No // code comments in section titles or fake compiler tags', pass: true },
              { rule: 'No Hallucinated Scoreboards: No arbitrary novelty or innovation scores', pass: true },
              { rule: 'WCAG AA Compliance: Contrast ratio on buttons & text >= 4.5:1 (Travertine is 6.8:1)', pass: true },
              { rule: 'No Orphan Headline Words: text-wrap balance enforced across all display heads', pass: true },
              { rule: 'Single-Elevation Layout: Flat spatial grid without nested cards within cards', pass: true },
            ].map((check, i) => (
              <div key={i} className="flex items-center justify-between rounded border border-neutral-800/80 bg-neutral-950 p-2 text-[11px]">
                <span className="text-neutral-300">{check.rule}</span>
                <span className="font-mono text-emerald-400 flex items-center gap-1">
                  <CheckCircle2 className="h-3.5 w-3.5" />
                  VERIFIED
                </span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Tab: CODE & DELIVERABLES */}
      {activeSubTab === 'code' && (
        <div className="rounded-xl border border-neutral-800 bg-neutral-900/60 p-5 space-y-4">
          <div className="flex items-center justify-between border-b border-neutral-800 pb-3">
            <div>
              <h3 className="text-sm font-semibold text-neutral-200">
                Production Deliverables & Export
              </h3>
              <div className="text-xs text-neutral-400">
                Single-file React + Tailwind v4 component ready for deployment
              </div>
            </div>

            <button
              onClick={handleCopyCode}
              className="flex items-center gap-1.5 rounded-md bg-amber-400 px-3 py-1.5 text-xs font-semibold text-neutral-950 hover:bg-amber-300 transition-colors"
            >
              {copiedCode ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
              <span>{copiedCode ? 'Copied to Clipboard' : 'Copy Component Code'}</span>
            </button>
          </div>

          <div className="rounded-lg border border-neutral-800 bg-neutral-950 p-4 font-mono text-xs text-neutral-300 overflow-x-auto">
            <pre>{`// Apex Studio Landing Page Component
// Generated by Sammypopi Multi-Agent Atelier (Samsonite, Sammy, Samkindle, Samuel)
export default function ApexLandingPage() {
  return (
    <div className="bg-[#0A0A0C] text-[#F4F4F5] min-h-screen">
      <header className="border-b border-white/10 px-6 py-4 flex justify-between items-center">
        <span className="font-semibold tracking-tight text-lg">Apex Architecture</span>
        <nav className="flex gap-6 text-sm text-neutral-400">
          <a href="#commissions">Commissions</a>
          <a href="#philosophy">Philosophy</a>
          <a href="#inquiry">Inquire</a>
        </nav>
      </header>
      <main className="max-w-7xl mx-auto px-6 py-20">
        <h1 className="text-5xl font-bold tracking-tight text-balance">
          ${project.designDraft.headline}
        </h1>
        <p className="mt-4 text-neutral-400 text-lg max-w-2xl">
          ${project.designDraft.subheadline}
        </p>
      </main>
    </div>
  );
}`}</pre>
          </div>
        </div>
      )}

    </div>
  );
};
